'use client'

export default function Footer({}: {}) {
  return (
    <footer className="mt-10 space-y-4 text-xs">
      <p>
        <b>Total Duration</b> stands for the amount of time passed between the
        initial request and the llm result arriving in the UI. It depends on the
        length of the output generated by the LLM. It&apos;s expected to be
        higher in Upstash Workflow.
      </p>

      <p>
        <b>Vercel Function Duration</b> stands for the amount of time a vercel
        function has been awake, executing or waiting for a response. It&apos;s
        much higher in the Regular Call case because the function has to wait
        for LLM to finish. In the case of Upstash Workflow, QStash waits for the
        LLM so function duration is much lower.
      </p>

      <p>
        <b>Approximate Cost</b> is calculated by multipliying the vercel
        function duration with the cost per second for the Basic Function in
        Vercel. The lowest possible cost per second for Vercel&apos;s cheapest 1
        GB function is calculated as{' '}
        <a
          href="https://vercel.com/docs/functions/usage-and-pricing#node.js-python-ruby-and-go-runtimes"
          target="_blank"
        >
          $0.18
        </a>{' '}
        ÷ 3600, which equals $0.00005 per second. For the calculation of
        Workflow, we also include{' '}
        <a href="https://upstash.com/pricing/qstash" target="_blank">
          the QStash cost, which is $1 per 100k messages
        </a>
        . Each workflow in this example makes 4 QStash requests. Cost of OpenAI
        is not included.
      </p>
    </footer>
  )
}
