import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Upstash Workflow",
  description: "Generated by create next app",
  icons: [
    "/upstashlogo.png"
  ]
  
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/upstashlogo.png" sizes="any"/>
      </head>
      <body className={inter.className + " text-black"}>{children}</body>
    </html>
  );
}
